FROM node:18

# dossier de travail
WORKDIR /usr/src/app

# copier package.json et installer deps
COPY package*.json ./
RUN npm install

# copier le reste du code
COPY . .

EXPOSE 3000
CMD ["npm", "run", "start:dev"]
